# Generated by Django 3.2.10 on 2024-03-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packageID', models.CharField(max_length=20, null=True)),
                ('packagename', models.CharField(max_length=20, null=True)),
                ('userName', models.CharField(max_length=20, null=True)),
                ('review', models.CharField(max_length=20, null=True)),
                ('rating', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
