# Generated by Django 3.2.10 on 2024-03-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0003_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=20, null=True)),
                ('number', models.CharField(max_length=20, null=True)),
                ('packageID', models.CharField(max_length=20, null=True)),
                ('packagename', models.CharField(max_length=20, null=True)),
                ('count', models.CharField(max_length=20, null=True)),
                ('date', models.CharField(max_length=20, null=True)),
                ('type', models.CharField(max_length=20, null=True)),
                ('city', models.CharField(max_length=20, null=True)),
                ('amount', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
