# Generated by Django 3.2.10 on 2024-03-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0006_package_packagetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.IntegerField(max_length=50, null=True),
        ),
    ]
